richardpenman/whois

MANIFEST.in

This is a good practice, and distributions like Fedora tend to require it in
their packaging guidelines.

Add the license file to the dist

---

whois/parser.py
whois/whois.py

This adresses some hundreds of `DeprecationWarning` from `pywhois`,
when used in a project of mine (running py3.7.6) . Variations of:
DeprecationWarning: invalid escape sequence \.
DeprecationWarning: invalid escape sequence \w
DeprecationWarning: invalid escape sequence \s
This should prepare `pywhois` for these being upped to printed
`SyntaxWarning`s and later `SyntaxError`s, in future Python 
versions, as per: https://bugs.python.org/issue32912
This tests fine on py2 and py3, with the same errors I see with `master`:
```
(python-2.7.3) me@my-machine:~/git-reps/pywhois$ python -m unittest discover test
..Error trying to connect to socket: closing socket
.Error trying to connect to socket: closing socket
......google.at 	(updated_date):	 ['20110426 17:57:27', '20110111 00:07:31', …
```

Syntax fix: For regexes, replace unicode strings with raw strings

---

whois/whois.py

Without this, the library throws a connection error.

Add support for .chat tld.

---

test/test_parser.py
whois/parser.py

All domains in .nl TLD become quarantined for 40 days upon cancellation.
This makes it effectively the expiration date.
For more information, have a look at:
https://www.sidn.nl/en/news-and-blogs/quarantine-period-end-times-to-be-shown-in-whois

Add expiration_date for .nl TLD

---

whois/parser.py

At some point, .mobi whois started using `Name Server:` for their nameserver listings, as opposed to `Nameservers:`.  This PR copies over the `WhoisMe` definitions which `WhoisMobi` was previously inheriting from, and makes that one change.
As an example domain, see `dotmobi.mobi`.  Thx!

Fix nameservers for .mobi

---

whois/whois.py

Hello!  My PR #77 added in a `quiet` parameter to `NICClient.whois` -- this one exposes that boolean up to `NICClient.whois_lookup` as well.  I've written a whois-monitoring script using python-whois which should ideally only generate output on certain circumstances, so it'd be useful to have `quiet` available there.  (The project, FYI: https://github.com/apocalyptech/pywhoishistory)
Thanks!
-CJ

Supply a 'quiet' argument to 'whois_lookup'

---

README.rst
whois/parser.py

GitHub redirects from [richardpenman/pywhois](https://github.com/richardpenman/pywhois) to [richardpenman/whois](https://github.com/richardpenman/whois). This change updates the repository path and title accordingly.

[Chore] Update repo paths

---

setup.py
whois/whois.py

This fixes the issue with some "new" TLDs currently not working. Example : go.live, swarm.space, okbeauty.store , etc...
Close #134

Use whois.nic.<tld> when <tld>.whois-servers.net does not exist

---

whois/parser.py

Whois server now returns "Domain not found" instead of "NOT FOUND" (but kept the old check for backward compatibility)

Fixed check for .org domain again

---

whois/parser.py

Adds support for the `Registrant ID` & `Eligibility Type` fields from auDA.
This is useful as `Registrant ID` will typically contain the ABN (Australian Business Number) that a domain is registered with. Similarly, `Eligibility Type` provides further details on the type of company, which could be useful.

Add more fields for .au domains

---

whois/parser.py

Add new date format.

---

whois/parser.py

I don't really code in Python, but this PR adds some basic support for `.edu` domains to parse the creation/expiration dates. Still requires additional later work for other fields.
Currently:
```
{'domain_name': 'SRU.EDU', 'registrar': None, 'whois_server': None, 'referral_url': None, 'updated_date': None, 'creation_date': None, 'expiration_date': None, 'name_servers': None, 'status': None, 'emails': None, 'dnssec': None, 'name': None, 'org': None, 'address': None, 'city': None, 'state': None, 'registrant_postal_code': None, 'country': None}
```
With this PR:
```
{'domain_name': 'SRU.EDU', 'creation_date': datetime.datetime(1993, 1, 20, 0, 0), 'expiration_date': datetime.datetime(2024, 7, 31, 0, 0)}
```

Add very basic support for .edu domains

---

whois/parser.py

Turns:
```
>>> whois.whois('island.gg')
{'domain_name': None, 'registrar': None, 'whois_server': None, 'referral_url': None, 'updated_date': None, 'creation_date': None, 'expiration_date': None, 'name_servers': None, 'status': None, 'emails': None, 'dnssec': None, 'name': None, 'org': None, 'address': None, 'city': None, 'state': None, 'registrant_postal_code': None, 'country': None}
```
into
```
>>> whois.whois('island.gg')
{'domain_name': 'island.gg', 'registrar': 'Sav.com LLC (https://www.sav.com)', 'creation_date': datetime.datetime(2023, 3, 3, 0, 5, 14, 551000)}
```

Add basic support for .gg

---

whois/parser.py

Add support for .rs ccTLD WHOIS format.  Fixes #106.
Turns
```
>>> whois.whois('google.rs')
{'domain_name': 'google.rs', 'registrar': 'Webglobe d.o.o.', 'whois_server': None, 'referral_url': None, 'updated_date': None, 'creation_date': None, 'expiration_date': datetime.datetime(2024, 10, 3, 12, 31, 19), 'name_servers': None, 'status': ['Active https://www.rnids.rs/en/domain-name-status-codes#Active', 'clientUpdateProhibited https://www.rnids.rs/en/domain-name-status-codes#ClientUpdateProhibited'], 'emails': None, 'dnssec': None, 'name': None, 'org': None, 'address': None, 'city': None, 'state': None, 'registrant_postal_code': None, 'country': None}
```
into
```
>>> whois.whois('google.rs')
{'domain_name': 'google.rs', 'status': ['Active …
```

Add parser support for .rs ccTLD WHOIS

---

whois/parser.py

The .ch ccTLD uses a `before YYYY-MM-DD` date format for some domains, including its own `nic.ch`:
```
First registration date:
before 1996-01-01
```
This fix turns `'creation_date': 'before 1996-01-01'` into `'creation_date': datetime.datetime(1996, 1, 1, 0, 0)`.

Add 'before %Y-%m-%d' date format for nic.ch

---

whois/whois.py

Hostnames ending with .sg domain are unable to resolve.
Let's add an entry for the SGNIC server.

Add NIC server for Singapore

---

whois/parser.py

In the original code name_servers were not provided for .at and .be domains. In this fix it is added for both. Besides domain_name, status and creation_date has been added for .be.

Fixing format for .at and .be tld

---

whois/parser.py

A quick change to the parser of NS for .UK domain names.
Currently, it only returns the first entry:
```
>>> from whois import whois
>>> whois("brixly.uk").name_servers
'justin.ns.cloudflare.com'
>>> whois("google.uk").name_servers
'ns1.googledomains.com'
```
Suggested change works with any number:
```
>>> from whois import whois
>>> whois("brixly.uk").name_servers
['justin.ns.cloudflare.com', 'mira.ns.cloudflare.com']
>>> whois("google.uk").name_servers
['ns1.googledomains.com', 'ns2.googledomains.com', 'ns3.googledomains.com', 'ns4.googledomains.com']
```

Update regex for UK NS parser

---

build/lib/whois/parser.py
build/lib/whois/whois.py
whois/parser.py
whois/whois.py

Ensure .dk domains get passed to the `WhoisDk` parser and host. Add the registrar regex, so that registrars are also picked up for `.dk` domains.

Fixes for the parser and handling of .dk domains

---

whois/parser.py

yahoo-net.jp Some whois information of the domain name cannot be obtained.
WHOIS command.
```
Domain Information: [ドメイン情報]
[Domain Name]                   YAHOO-NET.JP
[登録者名]                      LINEヤフー株式会社
[Registrant]                    LY Corporation
[Name Server]                   ns01.yahoo.co.jp
[Name Server]                   ns02.yahoo.co.jp
[Name Server]                   ns11.yahoo.co.jp
[Name Server]                   ns12.yahoo.co.jp
[Signing Key]
[登録年月日]                    2008/08/29
[有効期限]                      2024/08/31
[状態]                          Active
[ロック状態]                    DomainTransferLocked
[ロック状態]                    AgentChangeLocked
[最終更新]                      2024/04/11 16:21:56 (JST)
```

Complete the regex for parsing the WHOIS response results for .jp domains.

---

whois/parser.py

.pl nameservers are not parsed correctly. Here is a fix.
Example: test.pl
Whois response:
~~~
$ whois test.pl
DOMAIN NAME:           test.pl
registrant type:       organization
nameservers:           dns.home.pl. [217.160.80.244][2001:8d8:fe:53:6870::1]
dns2.home.pl. [2001:8d8:fe:53:6870::2][217.160.81.248]
dns3.home.pl. [2607:f1c0:fe:53:185:132:34:251][185.132.34.251]
created:               1998.08.12 13:00:00
last modified:         2023.07.31 13:55:46
renewal date:          2024.08.11 14:00:00
option created:        2023.01.25 10:47:15
option expiration date:       2026.01.25 10:47:15
dnssec:                Unsigned
REGISTRAR:
cyber_Folks S.A.
ul. Franklina Roosevelta 22
60-829 Poznań
Polska/Poland
tel.: +48.122963663
info@domeny.pl
WHOIS database responses: https://dns.pl/en/whois …

Fix regex for parsing .pl nameservers

---

whois/whois.py

Fixed #207 
```
% TCI Whois Service. Terms of use:
% https://tcinet.ru/documents/whois_ru_rf.pdf (in Russian)
% https://tcinet.ru/documents/whois_su.pdf (in Russian)
domain:        WHOIS.RU
nserver:       jessica.ns.cloudflare.com.
nserver:       trey.ns.cloudflare.com.
state:         REGISTERED, DELEGATED, VERIFIED
org:           Domain name registrar SALENAMES LTD.
taxpayer-id:   7705693660
registrar:     SALENAMES-RU
admin-contact: https://partner.salenames.ru/contact_admin.khtml
created:       1999-05-14T13:58:12Z
paid-till:     2025-05-31T21:00:00Z
free-date:     2025-07-02
source:        TCI
Last updated on 2024-04-26T10:56:30Z
```
fixed after
```
{'domain_name': 'WHOIS.RU',
'registrar': 'SALENAMES-RU',
'creation_date': datetime.datetime(1999, 5, 14, 13, 58, 12),
'expiration_date': …
```

Fixed .ru used correct nic server

---

whois/parser.py
whois/whois.py

Previously, `.studio` domains were not recognized nor fetched.

Add studio host

---

whois/parser.py

fix datetime.UTC, which doesn't work on all versions of Py3
I believe this was causing #221, because the date cast silently failed back to leaving the date as a string. I could be wrong, either way though this needed fixin'

Fix for #221

---

whois/parser.py

Pretty trivial change, but it seems to work :)
Fixes #228 
Before:
```
>>> import whois
>>> whois.whois("ns.tomis.ro")
{'domain_name': 'tomis.ro', 'domain_status': 'OK', 'registrar': 'ICI - Registrar', 'referral_url': 'http://www.rotld.ro', 'creation_date': 'Before 2001', 'expiration_date': datetime.datetime(2028, 5, 29, 0, 0), 'name_servers': ['ns1.lucaservices.ro', 'ns2.lucaservices.ro'], 'status': 'OK', 'dnssec': 'Inactive'}
```
After:
```
>>> import whois
>>> whois.whois("ns.tomis.ro")
{'domain_name': 'tomis.ro', 'domain_status': 'OK', 'registrar': 'ICI - Registrar', 'referral_url': 'http://www.rotld.ro', 'creation_date': datetime.datetime(2001, 1, 1, 0, 0), 'expiration_date': datetime.datetime(2028, 5, 29, 0, 0), 'name_servers': ['ns1.lucaservices.ro', 'ns2.lucaservices.ro'], …
```

Handle "before YYYY" entries

---

test/test_parser.py

The `test_com_allsamples` test is the only one that's using self.fail() instead of functions from the unittest.UnitTest class. Because of this, failures show a super obscure output that does not show the actual nature of the failure, which makes it really difficult to debug.
With `self.assert*()` at least when there is a difference in values, it will get shown, leading to easier debugging.

Standardize test assertions for sample files

---

test/samples/expected/nic.live
test/samples/whois/nic.live
whois/whois.py

Fixes #234 
`.live` domains have a known-authoritative server, `whois.nic.live`. This adds config and a sample for that TLD.

Add .live domain server config and sample

---

whois/parser.py

It's not a major change, just one line, but it adds the "reseller" field to the records, in case of need.  This can be useful to determine if a domain was purchased directly from the registrar, or from one of that registrar's resellers.

Added the "Reseller" field to the parser.

---

test/test_parser.py
whois/parser.py

* Add status field regex to .AI parser
```py
Python 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> w = whois.whois('tech.ai')
>>> w.status
'clientTransferProhibited https://icann.org/epp#clientTransferProhibited'
```
* Fix expiration date regex for .SITE and .DESIGN parsers
```py
Python 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> w = whois.whois('good.design')
>>> w.expiration_date
datetime.datetime(2025, 12, 14, 18, 47, 53)
>>> w = whois.whois('secure.site')
>>> w.expiration_date
datetime.datetime(2025, 8, 2, 23, 59, 59)
```

Small fixes for .AI, .SITE, .DESIGN parsers

---

whois/parser.py

The BR domain is using the "name_server" attribute in its regex whereas for all other domains the attribute is called "name_servers".
This PR is to standardize the BR domain to behave the same as all other domains and use the "name_servers" attribute name.

Fix name_server Attribute for BR domain

---

whois/parser.py

Apparently the return text for unregistered info domains has changed from "NOT FOUND" to "Domain not found".
This has been adjusted in class WhoisInfo accordingly

Adjust not found text for info domains

---

whois/parser.py

Apparently the return text for unregistered us domains has changed from "Not  found" to "No Data Found".
This has been adjusted in class WhoisUs accordingly

Adjust not found text for us domains

---

whois/__init__.py
whois/whois.py

Added optional flag `ignore_socket_errors: bool` to the `whois` method that allows to modify default handling of socket errors. With `ignore_socket_errors=False` whois will raise a socket exception instead of returning empty WHOIS data #277 .
Default is `ignore_socket_errors=True`.

Raise an exception on socket error

---

whois/parser.py

I was testing a variety of domains and found WhoisDomainNotFoundError wasn't raised all the times that it should.  This updates the logic for several TLDs
Thanks!

handle more WhoisDomainNotFoundError situations
