richardpenman/whois

whois/parser.py

I added 3 TLDs and fixed a couple of others

Fix support for a couple of TLDs

---

test/samples/expected/sapo.pt
test/samples/whois/sapo.pt
whois/parser.py

Update parser to new PT whois response format.

fix/update .pt parser

---

whois/whois.py

Mentioned by https://github.com/richardpenman/pywhois/issues/8

Add socks5 auth and fix socks proto initialization

---

whois/parser.py
whois/whois.py

added KZ parser

---

whois/parser.py

Bugfix WhoisHk Parser

---

whois/whois.py

s.connection and the code below is now inside a try-except. This way the whois.whois can do things like looping on an array of domains without execution the stopping in case of a socket timeout.

socket connection inside a try to prevent timeout errors

---

whois/whois.py

Add whois hosts for .dev, .games and .page GTLDs

add dev, games and page gtlds

---

whois/parser.py

Matching more then one name server in whois output of .eu domains.

Fix regex WhoisEu

---

whois/parser.py

Fix issue #44 and added updated_date support for .nl

Fix issue #44 and added updated_date support for .nl

---

whois/parser.py

Fixes issue #47 by adding alternatives to some of the WhoisJp regexes to match an alternative WHOIS format I've seen come from .jp domains.

Updates to WhoisJp regexes

---

whois/parser.py

* Many of the fields in the registration can have spaces in them
* Dates from Traficom always have the day first

Fixes for the FI parser

---

test/test_main.py
whois/__init__.py
whois/data/public_suffix_list.dat

See #50. I also included a public_suffix_list update since I'm working in that area, but I can split that into a separate PR if you want.

Handle second-level TLDs correctly when a first-level TLD doesn't exist

---

whois/parser.py
whois/whois.py

Add parser for .sg TLD
Updated DENICHOST with more informative one

Add parser for .sg TLD and update whois server for .de TLD    

---

whois/__init__.py

Added ability to explicity specify whois executable path

---

whois/parser.py

$ whois hkirc.hk|grep Expiry
Expiry Date: 16-11-2025

Fixes HK Expiry: HK always have the date first

---

whois/parser.py
whois/whois.py

I recently added two TLD domains: ooo and market. Accept my request pls

add tld ooo and market

---

whois/whois.py

I've been using this library as part of some automatic service monitoring, to let me know when domain names are getting closer to renewal.  One name in particular that I was monitoring, "netnet.us", includes this line in its whois output:
Registrar WHOIS Server: www.spiritdomains.com
... which causes `NICClient.whois()` to query again using that hostname.  In this case, it looks like that domain isn't actually responding to whois requests, so I'd be getting this on the console:
Error trying to connect to socket: closing socket
Fair enough, but that was screwing up our monitoring a bit by having that be the first line reported by the app.  (Instead of reporting the days-to-expiry, I'd just get the socket error.)
Anyway, this PR makes it so that "nhost" redirection doesn't actually output …

Don't show an error on STDOUT on nhost socket errors

---

whois/parser.py

Fix for Irish domains - also removes defunct queries.

Fix / Update parser.py for .ie domains

---

whois/parser.py
whois/whois.py

Hello, please, you can merge my code for support lt domains.
Thank you.

Support for lt domains

---

setup.py
whois/__init__.py

Add an option to include raw whois, [in the same way the IPwhois library does](https://github.com/secynic/ipwhois/blob/master/ipwhois/whois.py#L559-L560)
Close #131

add an option to include raw whois

---

whois/__init__.py
whois/whois.py

complete the work started in #87

use logger.error() instead of print()

---

whois/parser.py

The whois reply for .by domains differed from what the parser expected. This should improve it.

Fixes for .by domain parser

---

whois/whois.py

Added `whois.nic.net.ng` registry server for .ng domains

chore: add .ng registry WHOIS server

---

whois/parser.py
whois/whois.py

1. Added several TLDs
2. Fixed small typos
3. Formatted in accordance with PEP 8 requirements a little

Update whois.py and parser.py with several TLDs

---

whois/parser.py
whois/whois.py

Hi, thanks for this project.
My minor contribution.

add .pp.ua and .укр registries WHOIS servers

---

test/test_parser.py
whois/parser.py
whois/whois.py

Includes whois url endpoint, parser and test for the parser.

Add .bw TLD

---

whois/parser.py
whois/whois.py

you can test it on this domain: https://bekci.site

added: .site domain support

---

whois/parser.py

It was necessary to set dayFirst to true for .CZ domains.
https://www.nic.cz/whois/domain/aaaa.cz/
Expiration date | 2024-03-17 - Y.m.d

parser.py - fixed cz domain date parser for dayFirst set to true

---

whois/whois.py

add an empty string check. one of the commit is useless, i do not know how to delete it, so you can just ignore it.

fix https://github.com/richardpenman/whois/issues/175

---

whois/parser.py

An indent error occured in parser.py because of deleted line,  when resolving conflicts I think

changed: fixed indent error in parser.py

---

whois/parser.py

There is a missing part of init function.

Fix syntax error

---

whois/parser.py
whois/whois.py

The .design domain already configured but was using "WhoisRuServer", but it was not working, I changed TLD to "whois.nic.design".
I tested with domain: "https://baht.design/"

Fix design domain

---

whois/whois.py

Adding a quick timeout option to whois.whois()

---

whois/whois.py

Move socket creation to external func, to reuse it in findwhois_iana with proxy

findwhois_iana with proxy

---

whois/parser.py

Add new parser for .co domains that catches the error message for non-existent domains ("No Data Found")

Add new parser for .co domains

---

whois/parser.py

Updated WhoisRu parser to extract 'free_date' information from .ru domain whois data

Added 'free_date' regex pattern to WhoisRu parser

---

README.md
test/test_main.py
test/test_nicclient.py
test/test_parser.py
test/test_query.py
whois/__init__.py
whois/parser.py
whois/whois.py

self.regex was missing.
I've also added a test for WhoisUnknownDateFormatError and reorganize imports

fix example in readme + WhoisUnknownDateFormatError test

---

whois/parser.py
whois/whois.py

Added support for .ga TLD (ex-Freenom).

.ga TLD support (freenom)

---

README.md

added proxy config to README.md

added proxy config to README.md

---

whois/__init__.py

remove logger configuration

---

whois/parser.py

Fixes #288 (typo in the .edu parser) and works toward #275 for the `updated_date` fields.

Fix `updated_date` fields.

---

test/samples/expected/google.hu
test/samples/whois/google.hu
whois/parser.py

This adds support for parsing .hu responses.

add .hu parser
